// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Block struct {
	Hash                string  `json:"hash"`
	Number              string  `json:"number"`
	Time                string  `json:"time"`
	ParentHash          string  `json:"parentHash"`
	Difficulty          string  `json:"difficulty"`
	GasUsed             string  `json:"gasUsed"`
	GasLimit            string  `json:"gasLimit"`
	Nonce               string  `json:"nonce"`
	Miner               string  `json:"miner"`
	Size                float64 `json:"size"`
	TransactionRootHash string  `json:"transactionRootHash"`
	ReceiptRootHash     string  `json:"receiptRootHash"`
}
